//GETTERS
export const GET_TODO = "GET_TODOS"

//MUTATIONS
export const ADD_TODO = "ADD_TODO" 
export const REMOVE_TODO = "REMOVE_TODO"

//ACTIONS
export const ADD_TODO_ACTION = 'ADD_TODO_ACTION'
export const REMOVE_TODO_ACTION = 'REMOVE_TODO_ACTION'